build/qg-xxx: версия платформы Jetty в тестах зафиксирована на 12.1
Потому как Spring Boot переехал на неё, а самая актальная на данный момент версия WireMock - нет, и они бинарно не совместимы - без этого WireMock валится с:

Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'org.eclipse.jetty.util.component.Environment org.eclipse.jetty.util.component.Environment.ensure(java.lang.String)' [in thread "main @coroutine#3"]
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.<clinit>(ServletContextHandler.java:135)