build/qg-xxx: восстановлен возврат пустого тела со статусом 413 при попытке отправить mulitipart/file-data запрос более 10 МБ
В Spring Boot 4 интеграция с OAuth2-клиентом стала триггерить в этом случае SizeLimitExceededException:

org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (10485956) exceeds the configured maximum (10485760)
	at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl$1.raiseError(FileItemIteratorImpl.java:171)
	at org.apache.tomcat.util.http.fileupload.util.LimitedInputStream.checkLimit(LimitedInputStream.java:64)
	at org.apache.tomcat.util.http.fileupload.util.LimitedInputStream.read(LimitedInputStream.java:160)
	at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:263)
	at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:328)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
	at org.apache.tomcat.util.http.fileupload.util.LimitedInputStream.read(LimitedInputStream.java:157)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
	at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:119)
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:468)
	at org.apache.catalina.connector.Request.parseParts(Request.java:2576)
	at org.apache.catalina.connector.Request.doParseParameters(Request.java:2927)
	at org.apache.catalina.connector.Request.parseParameters(Request.java:2864)
	at org.apache.catalina.connector.Request.getParameterNames(Request.java:1122)
	at org.apache.catalina.connector.Request.getParameterMap(Request.java:1107)
	at org.apache.catalina.connector.RequestFacade.getParameterMap(RequestFacade.java:170)
	at jakarta.servlet.ServletRequestWrapper.getParameterMap(ServletRequestWrapper.java:169)
	at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest.getParameterMap(StrictHttpFirewall.java:788)
	at jakarta.servlet.ServletRequestWrapper.getParameterMap(ServletRequestWrapper.java:169)
	at jakarta.servlet.ServletRequestWrapper.getParameterMap(ServletRequestWrapper.java:169)
	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationCodeGrantFilter.matchesAuthorizationResponse(OAuth2AuthorizationCodeGrantFilter.java:187)